<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>StarFieldBuddy</PackageId>
    <Version>5.0.0</Version>
    <Title>StarFieldBuddy</Title>
    <Authors>dmanning23</Authors>
    <description>A MonoGame library to draw a shifting "hyperspace" starfield</description>
    <PackageProjectUrl>https://github.com/dmanning23/StarField</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/dmanning23/StarField</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>monogame</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Vector2Extensions" Version="5.*" />
  </ItemGroup>
</Project>